name: Python SDK quality checks and unit tests

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository code
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"
        cache: 'pipenv'

    - name: Install pipenv
      run: |
        pip install pipenv

    - name: Install dependencies
      run: |
        pipenv install --categories="packages,dev-packages,docs-packages"

    - name: Launch quality checks
      run: |
        pipenv run mypy
        pipenv run isort-check
        pipenv run black-check
        pipenv run ruff

    - name: Launch tests with pytest
      run: |
        pipenv run pytest
